import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import UCWindow from "../../components/common/UCWindow/UCWindow";
import {
  S1_ROSTER_SIZE,
  getS1RosterStats,
  loadS1Roster,
  removeS1RosterEntry,
  readS1Roster,
  saveS1RosterEntry,
  type S1ReviewDecision,
  type S1RosterSlot,
} from "../../services/s1Roster";
import { seedS1TournamentBracket } from "../../services/s1Tournament";
import "./SeasonRosterPage.css";

interface SeasonRosterPageProps {
  goBack: () => void;
  navigateTo: (page: "review") => void;
}

type Language = "zh" | "en";
type SeasonRosterId = "S1" | "S2" | "S3" | "S4";

const OFFICIAL_REVISION_REQUEST_KEY = "uce:review:official-revision-character-id";

interface RosterDraft {
  characterId: string;
  characterName: string;
  projectName: string;
  creator: string;
  reviewDecision: S1ReviewDecision;
  officialNotes: string;
}

const seasonModules: Array<{ id: SeasonRosterId; name: string; capacity: number; enabled: boolean }> = [
  { id: "S1", name: "起源", capacity: S1_ROSTER_SIZE, enabled: true },
  { id: "S2", name: "未定", capacity: S1_ROSTER_SIZE, enabled: false },
  { id: "S3", name: "未定", capacity: S1_ROSTER_SIZE, enabled: false },
  { id: "S4", name: "未定", capacity: S1_ROSTER_SIZE, enabled: false },
];

const emptyDraft: RosterDraft = {
  characterId: "",
  characterName: "",
  projectName: "",
  creator: "",
  reviewDecision: "pending",
  officialNotes: "",
};

const copy = {
  zh: {
    eyebrow: "SEASON ROSTER",
    title: "赛季参赛名单",
    subtitle: "按赛季管理参赛选手席位，避免审核误登记后无法移除。",
    back: "返回",
    slot: "席位",
    contestantId: "赛季参赛选手 ID",
    characterName: "角色名",
    projectName: "项目名称",
    creator: "作者",
    decision: "审核状态",
    notes: "备注",
    pending: "待复核",
    approved: "通过",
    rejected: "驳回",
    write: "写入 / 覆盖席位",
    clear: "清空席位",
    empty: "空位",
    occupied: "已登记",
    approvedCount: "已通过",
    pendingCount: "待复核",
    rejectedCount: "已驳回",
    total: "总席位",
    saved: "名单席位已更新。",
    cleared: "名单席位已清空。",
    missingId: "请填写赛季参赛选手 ID。",
    futureSeason: "该赛季名单管理位已预留。",
    rosterSeatTitle: "赛季名单席位",
    rosterSeatDescription: "用于登记官方选手，可增删、覆盖。",
    bracketSeatTitle: "随机对阵席位",
    bracketSeatDescription: "32 个有效名单满员后，由系统随机抽签生成。",
    seedBracket: "生成 S1 随机对阵",
    seedLocked: "需要 32 个通过 / 已导入 / 已训练席位才能抽签。",
    seeding: "正在生成随机对阵...",
    seeded: "S1 随机对阵已生成。",
    seedFailed: "S1 随机对阵生成失败",
    revise: "修正角色设计",
    reviseMissing: "请选择一个已登记的角色席位。",
  },
  en: {
    eyebrow: "SEASON ROSTER",
    title: "Season Roster",
    subtitle: "Manage season contestant slots independently from official review.",
    back: "Back",
    slot: "Slot",
    contestantId: "Season Contestant ID",
    characterName: "Character Name",
    projectName: "Project Name",
    creator: "Creator",
    decision: "Review Status",
    notes: "Notes",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    write: "Write / Overwrite Slot",
    clear: "Clear Slot",
    empty: "Empty",
    occupied: "Registered",
    approvedCount: "Approved",
    pendingCount: "Pending",
    rejectedCount: "Rejected",
    total: "Total Slots",
    saved: "Roster slot updated.",
    cleared: "Roster slot cleared.",
    missingId: "Enter a season contestant ID.",
    futureSeason: "This season roster management panel is reserved.",
    rosterSeatTitle: "Season Roster Slots",
    rosterSeatDescription: "Registers official season contestants; slots can be added, removed, or overwritten.",
    bracketSeatTitle: "Randomized Bracket Slots",
    bracketSeatDescription: "Generated by system draw only after all 32 valid roster slots are filled.",
    seedBracket: "Generate S1 Random Bracket",
    seedLocked: "Requires 32 approved / imported / trained slots before drawing.",
    seeding: "Generating randomized bracket...",
    seeded: "S1 randomized bracket generated.",
    seedFailed: "Failed to generate S1 randomized bracket",
    revise: "Revise Character",
    reviseMissing: "Select a registered character slot first.",
  },
};

function draftFromSlot(slot: S1RosterSlot | null): RosterDraft {
  if (!slot?.characterId.trim()) {
    return emptyDraft;
  }

  return {
    characterId: slot.characterId,
    characterName: slot.characterName,
    projectName: slot.projectName,
    creator: slot.creator,
    reviewDecision: slot.reviewDecision,
    officialNotes: slot.officialNotes,
  };
}

export default function SeasonRosterPage({ goBack, navigateTo }: SeasonRosterPageProps) {
  const { i18n } = useTranslation();
  const lang: Language = i18n.language.startsWith("en") ? "en" : "zh";
  const t = copy[lang];
  const [selectedSeasonId, setSelectedSeasonId] = useState<SeasonRosterId>("S1");
  const [selectedSlot, setSelectedSlot] = useState(1);
  const [roster, setRoster] = useState<S1RosterSlot[]>(() => readS1Roster());
  const [draft, setDraft] = useState<RosterDraft>(() => draftFromSlot(readS1Roster()[0] ?? null));
  const [status, setStatus] = useState("");
  const [seeding, setSeeding] = useState(false);

  const selectedSeason = seasonModules.find((season) => season.id === selectedSeasonId) ?? seasonModules[0];
  const selectedS1Slot = selectedSeasonId === "S1" ? roster[selectedSlot - 1] ?? null : null;
  const rosterStats = useMemo(() => getS1RosterStats(roster), [roster]);
  const canSeedS1Bracket = selectedSeasonId === "S1" && rosterStats.approved >= S1_ROSTER_SIZE;

  useEffect(() => {
    let cancelled = false;
    const refreshRoster = () => {
      void loadS1Roster().then((nextRoster) => {
        if (!cancelled) {
          setRoster(nextRoster);
        }
      });
    };

    refreshRoster();
    window.addEventListener("uce:s1-roster-updated", refreshRoster);
    return () => {
      cancelled = true;
      window.removeEventListener("uce:s1-roster-updated", refreshRoster);
    };
  }, []);

  useEffect(() => {
    setDraft(draftFromSlot(selectedS1Slot));
  }, [selectedS1Slot, selectedSeasonId]);

  const writeSlot = async () => {
    if (selectedSeasonId !== "S1") {
      setStatus(t.futureSeason);
      return;
    }
    if (!draft.characterId.trim()) {
      setStatus(t.missingId);
      return;
    }

    try {
      const nextRoster = await saveS1RosterEntry({
        slot: selectedSlot,
        characterId: draft.characterId,
        characterName: draft.characterName || draft.characterId,
        projectName: draft.projectName,
        creator: draft.creator || "Unknown Creator",
        sourcePath: "season-roster-manager",
        reviewDecision: draft.reviewDecision,
        officialNotes: draft.officialNotes,
        checksum: "",
        reviewPackageStatus: "manual_roster_management",
      });
      setRoster(nextRoster);
      setStatus(t.saved);
    } catch (error) {
      setStatus(error instanceof Error ? error.message : String(error));
    }
  };

  const clearSlot = async (slot = selectedSlot) => {
    if (selectedSeasonId !== "S1") {
      setStatus(t.futureSeason);
      return;
    }

    try {
      const nextRoster = await removeS1RosterEntry(slot);
      setRoster(nextRoster);
      if (slot === selectedSlot) {
        setDraft(emptyDraft);
      }
      setStatus(t.cleared);
    } catch (error) {
      setStatus(error instanceof Error ? error.message : String(error));
    }
  };

  const seedBracket = async () => {
    if (selectedSeasonId !== "S1") {
      setStatus(t.futureSeason);
      return;
    }
    if (!canSeedS1Bracket) {
      setStatus(t.seedLocked);
      return;
    }

    setSeeding(true);
    setStatus(t.seeding);
    try {
      await seedS1TournamentBracket();
      setStatus(t.seeded);
      window.dispatchEvent(new CustomEvent("uce:s1-tournament-updated"));
    } catch (error) {
      setStatus(`${t.seedFailed}: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setSeeding(false);
    }
  };

  const reviseSelectedCharacter = () => {
    const characterId = selectedS1Slot?.characterId.trim();
    if (selectedSeasonId !== "S1" || !characterId) {
      setStatus(t.reviseMissing);
      return;
    }

    window.sessionStorage.setItem(OFFICIAL_REVISION_REQUEST_KEY, characterId);
    navigateTo("review");
  };

  const renderS1Slot = (slot: S1RosterSlot) => {
    const occupied = Boolean(slot.characterId.trim());
    return (
      <article
        className={`season-roster-slot season-roster-slot-${slot.status} ${selectedSlot === slot.slot ? "season-roster-slot-active" : ""}`}
        key={slot.slot}
        onClick={() => setSelectedSlot(slot.slot)}
      >
        <div className="season-roster-slot-head">
          <strong>#{String(slot.slot).padStart(2, "0")}</strong>
          <span>{occupied ? t.occupied : t.empty}</span>
        </div>
        <h3>{slot.characterName || slot.characterId || t.empty}</h3>
        <p>{slot.projectName || slot.creator || "-"}</p>
        {occupied && (
          <button
            type="button"
            onClick={(event) => {
              event.stopPropagation();
              void clearSlot(slot.slot);
            }}
          >
            {t.clear}
          </button>
        )}
      </article>
    );
  };

  return (
    <UCWindow>
      <main className="season-roster-shell">
        <header className="season-roster-header">
          <div>
            <p>{t.eyebrow}</p>
            <h1>{t.title}</h1>
            <span>{t.subtitle}</span>
          </div>
          <button type="button" onClick={goBack}>{t.back}</button>
        </header>

        <section className="season-roster-tabs">
          {seasonModules.map((season) => (
            <button
              className={selectedSeasonId === season.id ? "season-roster-tab-active" : ""}
              key={season.id}
              type="button"
              onClick={() => {
                setSelectedSeasonId(season.id);
                setSelectedSlot(1);
                setStatus(season.enabled ? "" : t.futureSeason);
              }}
            >
              <strong>{season.id}</strong>
              <span>{season.name}</span>
            </button>
          ))}
        </section>

        <section className="season-roster-workspace">
          <aside className="season-roster-editor">
            <div className="season-roster-stats">
              <div><dt>{t.total}</dt><dd>{rosterStats.total}</dd></div>
              <div><dt>{t.occupied}</dt><dd>{rosterStats.occupied}</dd></div>
              <div><dt>{t.approvedCount}</dt><dd>{rosterStats.approved}</dd></div>
              <div><dt>{t.pendingCount}</dt><dd>{rosterStats.pending}</dd></div>
              <div><dt>{t.rejectedCount}</dt><dd>{rosterStats.rejected}</dd></div>
            </div>

            <section className="season-roster-seat-model">
              <article>
                <strong>{t.rosterSeatTitle}</strong>
                <span>{t.rosterSeatDescription}</span>
              </article>
              <article>
                <strong>{t.bracketSeatTitle}</strong>
                <span>{t.bracketSeatDescription}</span>
                <button
                  type="button"
                  onClick={seedBracket}
                  disabled={!selectedSeason.enabled || !canSeedS1Bracket || seeding}
                >
                  {seeding ? t.seeding : t.seedBracket}
                </button>
              </article>
            </section>

            <label>
              <span>{t.slot}</span>
              <select
                value={selectedSlot}
                onChange={(event) => setSelectedSlot(Number(event.target.value))}
                disabled={!selectedSeason.enabled}
              >
                {Array.from({ length: selectedSeason.capacity }, (_, index) => (
                  <option key={index + 1} value={index + 1}>
                    #{String(index + 1).padStart(2, "0")}
                  </option>
                ))}
              </select>
            </label>

            <label>
              <span>{t.contestantId}</span>
              <input
                value={draft.characterId}
                onChange={(event) => setDraft((current) => ({ ...current, characterId: event.target.value }))}
                disabled={!selectedSeason.enabled}
              />
            </label>

            <label>
              <span>{t.characterName}</span>
              <input
                value={draft.characterName}
                onChange={(event) => setDraft((current) => ({ ...current, characterName: event.target.value }))}
                disabled={!selectedSeason.enabled}
              />
            </label>

            <label>
              <span>{t.projectName}</span>
              <input
                value={draft.projectName}
                onChange={(event) => setDraft((current) => ({ ...current, projectName: event.target.value }))}
                disabled={!selectedSeason.enabled}
              />
            </label>

            <label>
              <span>{t.creator}</span>
              <input
                value={draft.creator}
                onChange={(event) => setDraft((current) => ({ ...current, creator: event.target.value }))}
                disabled={!selectedSeason.enabled}
              />
            </label>

            <label>
              <span>{t.decision}</span>
              <select
                value={draft.reviewDecision}
                onChange={(event) =>
                  setDraft((current) => ({ ...current, reviewDecision: event.target.value as S1ReviewDecision }))
                }
                disabled={!selectedSeason.enabled}
              >
                <option value="pending">{t.pending}</option>
                <option value="approved">{t.approved}</option>
                <option value="rejected">{t.rejected}</option>
              </select>
            </label>

            <label>
              <span>{t.notes}</span>
              <textarea
                value={draft.officialNotes}
                onChange={(event) => setDraft((current) => ({ ...current, officialNotes: event.target.value }))}
                disabled={!selectedSeason.enabled}
              />
            </label>

            <div className="season-roster-actions">
              <button type="button" onClick={() => void writeSlot()} disabled={!selectedSeason.enabled}>{t.write}</button>
              <button type="button" onClick={() => void clearSlot()} disabled={!selectedSeason.enabled}>{t.clear}</button>
              <button type="button" onClick={reviseSelectedCharacter} disabled={!selectedSeason.enabled || !selectedS1Slot?.characterId.trim()}>{t.revise}</button>
            </div>
          </aside>

          <section className="season-roster-grid">
            {selectedSeasonId === "S1"
              ? roster.map(renderS1Slot)
              : Array.from({ length: selectedSeason.capacity }, (_, index) => (
                  <article className="season-roster-slot season-roster-slot-empty season-roster-slot-disabled" key={index + 1}>
                    <div className="season-roster-slot-head">
                      <strong>#{String(index + 1).padStart(2, "0")}</strong>
                      <span>{t.empty}</span>
                    </div>
                    <h3>{selectedSeason.id}</h3>
                    <p>{t.futureSeason}</p>
                  </article>
                ))}
          </section>
        </section>

        <footer className="season-roster-footer">
          <span>{selectedSeason.id} / {selectedSeason.name}</span>
          {status && <strong>{status}</strong>}
        </footer>
      </main>
    </UCWindow>
  );
}
